---
# 20180430 Modified in order to pass w/o editing yaml files that are already committed
# (default value taken at http://yamllint.readthedocs.io/en/v1.5.0/configuration.html
# and left out as a comment in each line).
rules:
  braces:
    min-spaces-inside: 0
    max-spaces-inside: 0
  brackets:
    min-spaces-inside: 0
    max-spaces-inside: 1
  colons:
    max-spaces-before: 0
    max-spaces-after: 1
  commas:
    max-spaces-before: 0
    min-spaces-after: 0  # 1
    max-spaces-after: 2  # 1
  comments:
    level: warning
    require-starting-space: yes
    min-spaces-from-content: 2
  comments-indentation:
    level: warning
  document-end: disable
  document-start:
    level: warning
    present: yes
  empty-lines:
    max: 2
    max-start: 0
    max-end: 1  # 0
  hyphens:
    max-spaces-after: 1
  indentation:
    spaces: consistent
    indent-sequences: whatever
    check-multi-line-strings: no
  key-duplicates: enable
  line-length:
    max: 128  # 80
    allow-non-breakable-words: yes
    allow-non-breakable-inline-mappings: no
  new-line-at-end-of-file: disable  # enable
  new-lines:
    type: unix
  trailing-spaces: disable  # enable
  truthy:
    level: warning
